[package]
name = "winedroid-compiler"
description = "Ahead-of-time native compiler for WineDroid"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lib]
name = "winedroid_compiler"
path = "src/lib.rs"

[[bin]]
name = "winedroid-aot"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
winedroid-core = { path = "../winedroid-core" }
zip.workspace = true

[[bin]]
name = "winedroid-sukisu-link"
path = "src/sukisu_link_main.rs"

[[bin]]
name = "winedroid-sukisu-recursive"
path = "src/recursive_main.rs"
