[package]
name = "winedroid-cli"
description = "Command-line interface for WineDroid"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "winedroid"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
serde_json.workspace = true
winedroid-core = { path = "../winedroid-core" }
